### PR TITLE
Fines & Fees payment improvements

### PR DESCRIPTION
**Pull request by chryslovelace**
Supports paying individual fees or all fees at once. Input fields now autofill with the full amount of each fee or the total amount for all allowed fees.

### CODE REVIEW

**Comment by alex-wreschnig** [comment]
On [line 868 of custom.js](https://github.com/ulsdevteam/primove-default-view/pull/29/commits/747db0f0b2fcef621ef76383214c95913749dbfe#diff-d6666d0b60b393ffcc634f3a265293830eb04ead789746ada08dd1882331afbfR868), are we expecting to not need to deal with Europeans (et al.) who might use commas as the decimal separator?

**Comment by chryslovelace** [comment]
It does seem like it renders the fee amounts with commas when I switch the language to Spanish, but it also resets the link when it changes languages. I'll probably need to find another way to grab the link so that works. I'm also not sure if PHP will parse numbers with commas by default so some changes might be needed in the microservice as well.

**Comment by ctgraham** [comment]
We only support payments in USD, and we can require USD formatting.

**Comment by alex-wreschnig** [comment]
> We only support payments in USD, and we can require USD formatting.

Excellent. @chryslovelace , @ctgraham : Do we need to do anything in order to enforce this requirement? If not, I'm good with the PR.

**Comment by chryslovelace** [comment]
I added a check so that if that regex fails, it will just leave the input fields blank instead of throwing an error.

**Review by ctgraham — CHANGES_REQUESTED** [review]
Let's pull the ReShare integration out of this branch, leaving it just to `dev-1.8-reshare-integration`.  I think @alex-wreschnig had additional work on it that was identified after a recent ExL monthly update.

**Pull request merged**
